apiVersion: v1
kind: Secret
metadata:
  name: servicenow-ticketing-runtime-secret
  namespace: network-compliance-ticketing
type: Opaque
stringData:
  TICKETING_DB_USER: "REPLACE_WITH_DB_RUNTIME_USER"
  TICKETING_DB_PASSWORD: "REPLACE_WITH_DB_RUNTIME_PASSWORD"
  TICKETING_SERVICENOW_AUTHORIZATION: "REPLACE_WITH_SERVICENOW_AUTHORIZATION"
